### ISSUE TITLE
Does not install properly

### ISSUE THREAD

**Issue by JackPenry** [sopel-irc/sopel-youtube#19]
On Ubuntu 18.04 using Python 3.6.9,  I installed sopel-youtube with `python3 setup.py install`
Upon executing `sopel configure` I received the following error:
`NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.6/dist-packages/sopel_modules.youtube-0.2.0-py3.6.egg/sopel_modules'`
`/usr/local/lib/python3.6/dist-packages/sopel_modules.youtube-0.2.0-py3.6.egg` was installed to the directory as an archive, and I had to extract it to a directory of the same name to get the module to work.

**Comment by dgw** [comment]
Your installation command should have printed a warning that the plugin won't load properly:

```
$ python3 setup.py install
Sopel does not correctly load modules installed with setup.py directly. Please use
"pip install .", or add /home/dgw/github/sopel-youtube/sopel_modules to core.extra
in your config.
```

We don't support installing with `setup.py`. You [probably shouldn't use it](https://stackoverflow.com/a/1550235/5991) anyway.

**Comment by JackPenry** [comment]
I got no such error message that I recall, but I exited the ssh session and there's no way for me to know right now. It definitely did not come at the end of any command I executed, and I installed it once again as root as I didn't know what the issue was at first and didn't really think about it. I would suggest adding proper installation information to the repository, then. Sopel.chat contains no information about this plugin that I can find easily; I just knew there was one because I know of an IRC that uses it. I found this repo searching 'sopel youtube plugin' on DDG. Sopel was installed using `setup.py` there was absolutely no reason for me to believe I shouldn't install it as such.

**Comment by dgw** [comment]
Sopel itself might work if installed with `setup.py` but it's not an "officially supported" method. We don't test it. Its instructions ([README](https://github.com/sopel-irc/sopel#installation) & [website](https://sopel.chat/usage/installing/)) also say to use pip.

But sure, I'll add a brief section to the README here on how to install this plugin.

**Comment by JackPenry** [comment]
Hey I'm not claiming to be anything other than a puzzled end-user.
And from your link which I actually used to install Sopel:

> In the source directory (whether cloned or from the tarball) run python setup.py install. You can then run sopel to configure and start the bot. Alternately, you can just run the sopel.py file in the source directory.

**Comment by dgw** [comment]
> And from your link which I actually used to install Sopel:

Thanks for telling me. That must have been overlooked in the documentation overhaul for 7.0. I'll get it fixed, too.

**Comment by JackPenry** [comment]
Sure, and thank you for the fast response.
