### ISSUE TITLE
Request: Subscriber count info item

### ISSUE THREAD

**Issue by Strykar** [sopel-irc/sopel-youtube#26]
See https://github.com/dasu/syrup-sopel-modules/blob/master/youtoob.py for examples

**Comment by dgw** [comment]
I can't speak for the other developers involved here, but I'm not going to dig through source code for another plugin looking for vague "enhance"ment ideas. Specific requests are always welcome, however!

**Comment by Strykar** [comment]
@dgw Fair enough, the feature I fancy the most from that plugin is that besides posting the YT title, it also prints, Likes, Dislikes, Views, Channel Subscribers and the Total number of Comments.

**Comment by dgw** [comment]
Maybe customize the `info_items` setting? It's new in sopel-youtube 0.3.0.

https://github.com/sopel-irc/sopel-youtube/blob/963a1a561b596e0fba795c9f6fd79ee74e40b7af/sopel_modules/youtube/youtube.py#L65-L72

Looks like the channel's subscriber count is the only piece of data not already supported here.

**Comment by dgw** [comment]
@Strykar With apologies for the double-post, I wanted to let you know that the settings are now properly documented for the next release, as of 2e90dda337f0c7d3406bf3e043f9cf52dd9bb9ab—and to thank you for motivating me to write the new README section. 😸

**Comment by Strykar** [comment]
@dgw No, I should've gone through the file and noticed that, I'm sorry, it takes me a while as I don't know Python and I hadn't.
Should I keep this open till those are implemented :relieved:

Would you also consider a `--color` switch or something to enable colors for all the options displayed or `--no-colors` for any of the displayed options? Personally I like the colors but it may be a bit much for others.

**Comment by dgw** [comment]
Not sure what you mean by "switch". The primary trigger method for this plugin is when someone posts a link to YouTube; the search function is kind of secondary, and I don't know how useful colors are in general.

From your edit, I guess you realized that `votes` (and `votes_color`) are the like/dislike info. 😸

Since you say you don't know Python, I'll refrain from the usual "feel free to open a PR" spiel, but let's retitle the issue to be about adding a subscriber count info item and maybe it can get done before 0.3.2.

**Comment by dgw** [comment]
@Strykar I looked around a bunch of YouTube API documentation today and didn't see any way to get the uploader's subscriber count returned in the video details. The `youtoob` plugin you linked to from syrup doesn't appear to pull that info, either. 😕

**Comment by dgw** [comment]
Not worth sending a second API request to get this.
