### ISSUE TITLE
Use python_version markers to allow newer python versions to installer newer pip packages

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel-youtube#34]
Python 2.7 support is probably staying in sopel for a bit longer but in the interest of keeping packages up to date, it would be nice if we could use the most recent version of the google api client on newer versions of python.

I don't see anything obviously breaking blocking using a python_version markers and can send a PR if it's acceptable.

**Comment by dgw** [comment]
Hey @RhinosF1, I just realized that the upcoming 0.5.0 release already touches dependencies (to require Sopel 7.1+ instead of 7.0+) and this would also be a good time to tweak the API client requirements. Are you still interested in doing this?
