### ISSUE TITLE
Can't get past "before you continue" cookie pop-up

### ISSUE THREAD

**Issue by temotodochi** [sopel-irc/sopel-youtube#35]
URL module can't access youtube now without being stopped by googles cookie approval pop-up, and same thing seems to be happening with this youtube module. 

Not sure how this module is being triggered. Is it via URL module? URL module itself is being blocked by youtube and this module seems that it's not doing anything. It's supposed to get the video details via google api?

**Comment by dgw** [comment]
I can't reproduce any issue with this plugin.

```irc
<~dgw> Test again https://www.youtube.com/watch?v=Cjvtx3HMUks
<&Kaede> [YouTube] ⁨Karnivool - Simple Boy⁩ | Channel: ⁨JTbassist09⁩ | 5m 48s | 960,140 views | Friday, June 05, 2009 08:14:10 
```

Did you configure your API key?

**Comment by temotodochi** [comment]
Problem solved. I did configure my google api key, but turns out youtube api is disabled by default and must be explicitly enabled and the api key must be restricted by origin ip addresss.

**Comment by dgw** [comment]
Glad to hear it! If you see any places where the plugin's logging or messaging could be improved, please feel free to drop excerpts. I tested what happens when the API key is configured incorrectly a while ago, but maybe there are cases I missed and/or something changed!
