### ISSUE TITLE
bug: getting duplicate links?

### ISSUE THREAD

**Issue by ghost** [sopel-irc/sopel-youtube#59]
Can't test this on the official Sopel instance, so...

> https://music.youtube.com/watch?v=hXu5-7WLVtA&list=RDAMVMhXu5-7WLVtA
> [YouTube] ⁨Mix - Die Straße⁩ | Automatic Playlist/Mix
> [YouTube] ⁨Die Straße⁩ | 2020-11-26 - 10:17:54 UTC | Channel: ⁨Nachtmahr - Topic⁩ | 4m 53s
> 
> .version
> [version] Sopel v8.0.0.dev0 | Python: 3.11.6 | Commit: d212dd10e905fc2d90e5cf8284c24a7bbd270859
> 
> .version youtube
> [version] youtube v0.5.1

Only seems to happen with `music.youtube.com` links.

---

My config:

```
[youtube]
api_key = abc123
info_items =
	date
	uploader
	length
```

**Comment by ghost** [comment]
Not quite related: the first time someone posted that exact link, my sopel crashed and generated zero errors or logs...

I've enabled DEBUG and RAW logging in the hopes that something like this doesn't happen again...

Even after doing that, if I spam the original link, the bot eventually just crashes and there's nothing in the logs about it. I just see it got my message and then the logs are followed a few seconds later by startup stuff. :/

**Comment by dgw** [comment]
Read about the `playlist_watch` setting in the plugin's readme.

Spamming YT links might overload the Google API client library, not sure. This plugin doesn't do any caching. 🤷‍♂️
