### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by ghost** [sopel-irc/sopel-youtube#6]
Occasionally instead of printing a search result or information for a youtube link, the bot will print `BadStatusLine: '' (file "/usr/lib/python2.7/httplib.py", line 379, in _read_status)` rather than whatever it should have. Redoing the search or repasting the link immediately after the error has so far always resulted in a normal, successful bot response. Not sure what is going on, but the error occurs at least once every ten links/searches, or thereabout. Any ideas?

**Comment by kwaaak** [comment]
I also experienced this while running a sopel bot on Python2.7. It has not happened on a Python3 bot.

**Comment by dgw** [comment]
Not sure what to do with this four-year-old issue that hasn't seen so much as a "Me, too!" in three years. If it comes up again, then we'll give this another look.
