### ISSUE TITLE
python2 bad?

### ISSUE THREAD

**Issue by ghost** [sopel-irc/sopel-youtube#64]
https://github.com/sopel-irc/sopel-youtube/blob/afd3e3aee12dc29f2d1bf05565217bbca3eac372/sopel_youtube/__init__.py#L29-L30

**Comment by dgw** [comment]
I mean yes, but what do you want done about it? This will go away as part of dropping support for Sopel 7 when that time comes.

**Comment by ghost** [comment]
> I mean yes, but what do you want done about it? This will go away as part of dropping support for Sopel 7 when that time comes.

Now it won't be forgotten. 😝
